---
title: "Research"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

<style type="text/css">
.title {
  display: none;
}

</style>

# Job Market Paper

<div style="text-align: justify">

1. Agricultural trade policy and water quality: evidence from the Mexican Hass Avocado Import Program (sole author)

[Download the paper](papers/JobMarketPaper_WQ.pdf){target="_blank"}

    Abstract: This paper provides empirical evidence that the 2016 Mexican Hass Avocado Import Program amendment led to improved water quality due to Mexican avocado farmers incorporating cleaner production methods and applying less harmful pesticides to their avocados. Two-way fixed effects difference-in-differences analysis shows that the policy improved surface water quality, reducing biochemical oxygen demand (BOD) by approximately 12 percent and chemical oxygen demand (COD) by 11 percent. Further evidence suggests the amendment led to a 2 percent decrease in nitrate pollution and a nearly 1 percent increase in nitrites---likely stemming from cleaner avocado practices and increased avocado production.


</div>

# Working in Progress

<div style="text-align: justify">


1. Fracking and Tracking: The Effects of Oil and Natural Gas Well Locations on the Housing Market (with Brent Norwood, Ahmed El Fatmaoui, and Samantha Johnson)

[Download the paper](papers/Fracking and Tracking.pdf){target="_blank"}

    Abstract: Hydraulic fracturing or “fracking” has made it possible to produce vast new quantities of oil and natural gas causing states such as Colorado, Texas, and Oklahoma to dramatically increase their number of oil and natural gas wells. Using data from the U.S. Department of Homeland Security and Zillow’s ZTRAX, we estimate the effect of hydraulically fractured oil and natural gas well sites on both urban and rural residential home prices between 2000 and 2018. Utilizing ArcGIS, we create varying buffer zone sizes around well sites to explore how average home prices change before and after a well opens and apply a ZIP code-level fixed effects model, a household-level fixed effects model, a repeat sales model, and a spatial differences-in-differences (SDID) approach. Our results show that homes within 0.5 miles of a well have a 4.5% increase in selling price and homes between 0.5-1 mile of a well see a 2.5% increase in selling price compared to properties located more than 2 miles away from a well.



2. Guaconomics: Avocado Price Shocks and Crime Rates in Mexico (sole author)

[Download the paper](papers/Guaconomics.pdf){target="_blank"}

    Abstract:  Avocado trade between Mexico and the United States has exponentially burgeoned since 1997. Politicians have a growing concern about avocado production leading to more harm than good based on drug cartel involvement. Using data on 460 municipalities from 1997 to 2019, I exploit exogenous changes in U.S. weather deviations to show that increased Mexican avocado producer prices differentially decreased homicide in municipaliities more climatically suited to grow avocados. This is because of increased agricultural employment from exponential growth in avocado production. However, there are different time heterogeneous effects. I find evidence that after the war on drugs took place in 2006, higher prices differentially increased homicide as well as other crime indicators such as property crime, cattle theft, and reported threats. The heterogeneous effects stem from increased drug cartel presence in the avocado industry.

3. The Effects of Unbalanced FDI Inflow from Trade on the Gender Wage Gap in Mexico  (sole author)

[Download the paper](papers/FDI_GENDERWAGE.pdf){target="_blank"}

    Abstract:  There is an on going discussion of the numerous impacts of trade openness on Latin America’s economy. In this study, I assess how the Mexico-EU Free Trade Agreement (FTA) of 2000 affected Mexico’s gender wage gap. For Mexico, the policy encouraged FDI inflow from Europe; however, 91.5 percent of this FDI from Europe went to the Mexican states of the Mexico City Federal District, the state of Mexico, Nuevo Le´on, Jalisco, and Puebla. FDI inflow tends to benefit foreign manufacturing company wages for the host country. These companies predominantly employ men as oppose to women. This is because of the higher work skills men have on average compared to women in Mexico. I use survey data from the years 1995 to 2004 and apply a difference-in-differences model to assess the effect of the policy on gender wage inequality. The empirical findings show that there was a higher difference in men’s average monthly earnings and hourly wages compared to women after the enactment of the trade policy among these 5 states. The empirical evidence also indicates that there is no change in the average different amount of hours both genders work before and after the policy. My findings show that one cause for the gender wage gap increase in this region comes from the highly concentrated foreign direct investment inflow from the European Union.

</div>
