---
title: "Teaching"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

<style type="text/css">
.title {
  display: none;
}

</style>

# Instructor


##### Spring 2024

 - ECON 1113-995: Principles of Macroeconomics
  [Syllabus](teaching/ECON1113_995_Syllabus.pdf){target="_blank"}
  [Survey](teaching/ECON1113_995_SURVEY.pdf){target="_blank"}

 - ECON 1113-795: Principles of Macroeconomics (Concurrent high school students)
  [Syllabus](teaching/ECON1113_795_Syllabus.pdf){target="_blank"}
  [Survey](teaching/ECON1113_795_SURVEY.pdf){target="_blank"}
  

##### FALL 2023

 - ECON 1123-995: Principles of Microeconomics
  [Syllabus](teaching/ECON1123_995_Syllabus.pdf){target="_blank"}
  [Survey](teaching/ECON1123_995_SURVEY.pdf){target="_blank"}

 - ECON 1123-795: Principles of Microeconomics (Concurrent high school students)
  [Syllabus](teaching/ECON1123_795_Syllabus.pdf){target="_blank"}
  [Survey](teaching/ECON1123_795_SURVEY.pdf){target="_blank"}

##### Summer 2023

 - ECON 3713-300: Governmental Relations to Business
  [Syllabus](teaching/ECON3713_300_Syllabus.pdf){target="_blank"}
  [Survey](teaching/ECON3713_300_SURVEY.pdf){target="_blank"}


##### Fall 2022

 - ECON 2843: Elements of Statistics
  [Syllabus](teaching/ECON2843_SYLLABUS.pdf){target="_blank"}
  [Survey](teaching/ECON2843_850_SURVEY.pdf){target="_blank"}


##### Summer 2022

 - ECON 1123-200: Principles of Microeconomics
  [Syllabus](teaching/ECON1123_200_SYLLABUS.pdf){target="_blank"}
  [Survey](teaching/ECON1123_200_SURVEY.pdf){target="_blank"}


# Graduate Teaching Assistant


 - Econometric Analysis (ECON 4223), International Trade (ECON 3613), Labor Economics (ECON 3513), Health Economics (ECON 3523), Elements of Statistics (ECON 2843), Principles of Economics-Micro (ECON 1123)

